// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import { Category } from '@app/core/interfaces/categories';

export const environment = {
  production: false,
  hmr: false,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  sparqlLanguages: [
    { appLanguage: 'en-US', sparqlLanguage: 'en' },
    { appLanguage: 'fr-FR', sparqlLanguage: 'fr' }
  ],
  paginationItemsPerPage: 9
};

export const categoriesList: Category[] = [
  { name: 'fallacies', language: 'en', wd: 'Q186150', wdt: 'P31' },
  { name: 'cognitive_bias', language: 'en', wd: 'Q1127759', wdt: 'P31' }
];
